name: Ejecutar Pruebas Unitarias

on:
  push:
    branches:
      - main  # Puedes ajustar la rama según tu configuración

jobs:
  pruebas_unitarias:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v2

    - name: Configurar Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  

    - name: Ejecutar pruebas unitarias
      run: |
        python -m unittest discover -v -p "*test*.py"
